name: Daily News Workflow

on:
  schedule:
    - cron: '10 23 * * *'  # Executa às 23h UTC (20h10MIN Brasil)
  workflow_dispatch:  # Permite execução manual

jobs:
  fetch_news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          pip install requests

      - name: Rodar o script para coletar notícias e enviar e-mail
        run: |
          python scripts/fetch_news.py

      - name: Commit e push das notícias
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/news.json
          git commit -m "Atualizar notícias"
          git push
